more debugging…

diff --git a/.evergreen.yml b/.evergreen.yml
--- a/.evergreen.yml
+++ b/.evergreen.yml
@@ -145,7 +145,7 @@ functions:
           set -e
           export NODE_JS_VERSION=${node_js_version}
           source .evergreen/.setup_env
-          npm run test-ci
+          (npm run test-ci && echo "success" && true) || (echo "failure" && false)
           echo "Creating coverage tarball..."
           tar cvzf coverage.tgz coverage
     - command: s3.put
